#!/bin/bash

j=1
i=1

rm tCC.dat
cat "" > tCC.dat

#for i in 11  12  14  15	16  18  19  20  21  22  23  3  5  7  8  9;
for i in 3 5 7 8 9 11 12 14 15 16 18 19 20 21 22 23;
#for i in 301;
do

cat tCC.dat $i/cc_ec_final.dump > t2CC.dat
mv t2CC.dat tCC.dat

sed -i '/Gamma/d' tCC.dat


done 
